name: CI
on:
  push:
    branches:
      - v5

jobs:
  build-uiw-admin:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: yarn install
    - run: yarn run build
    - run: yarn run build:create

    # 生成文档
    - run: npm run www:build

    - name: Create README.md
      working-directory: ./examples/website/build
      run: |
        cat > README.md << EOF
        Documentation uiw-admin@v5
        ====
        Preview: https://raw.githack.com/uiwjs/uiw-admin/v5-doc/index.html
        EOF

    - name: 📦 publish to NPM
      uses: kktjs/npm-publish@main
      with:
        token: ${{ secrets.NPM_TOKEN }}
        workspaces: |
          packages/*
          !packages/markdown-navbar
          create-uiw-admin
          eslint-packages/config
        tag: bate

    - name: Deploy Website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: v5-doc
        publish_dir: ./examples/website/build
